/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei/native";
import OldTV from './OldTV.glb'

export default function Model(props) {
  const group = useRef();
  const { nodes, materials } = useGLTF(OldTV);
  return (
    <group ref={group} {...props} dispose={null}>
      <group position={[-0.02, 0.1, 0.03]} rotation={[-1.24, 0.06, 1.55]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.ﺺﻧ001.geometry}
          material={materials["Material.022"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.ﺺﻧ001_1.geometry}
          material={materials.tv}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.ﺺﻧ001_2.geometry}
          material={materials["1"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.ﺺﻧ001_3.geometry}
          material={materials.t1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.ﺺﻧ001_4.geometry}
          material={materials.t}
        />
      </group>
      <group position={[-0.02, 0.1, 0.03]} rotation={[-1.24, 0.06, 1.55]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.ﺺﻧ002.geometry}
          material={materials["Material.001"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.ﺺﻧ002_1.geometry}
          material={materials["tv.001"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.ﺺﻧ002_2.geometry}
          material={materials["1.001"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.ﺺﻧ002_3.geometry}
          material={materials["t1.001"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.ﺺﻧ002_4.geometry}
          material={materials["t.001"]}
        />
      </group>
    </group>
  );
}

useGLTF.preload(OldTV);
